import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import FrontLayout from '../components/Front/FrontLayout'
import AudioLayout from '../components/Audio/AudioLayout/AudioLayout'


export default function Home() {
    // console.log('yeah')
    return (
        // <FrontLayout>
        <AudioLayout>

        <div>
            <Head>
                <title>xk-audio-filesharing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico?v=1.1" />
            </Head>
            <h1>empty home</h1>
            <footer>
            </footer>
        </div>
        </AudioLayout>
        // </FrontLayout>
    )
}
