import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import FrontLayout from '../components/Front/FrontLayout'


export default function Home() {
    return (
        <FrontLayout>
        <div>
            <Head>
                <title>xk-audio-filesharing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico?v=1.1" />
            </Head>
            <h1>Dylan King</h1>
            <Link href="/work/">
                Artist Login
            </Link>

            <footer>
            </footer>
        </div>
        </FrontLayout>
    )
}
